module.exports = {
  icalcreg1: '[hh:mm] Time of regeneration 1',
  icalcreg2: '[hh:mm] Time of regeneration 2',
  icalcreg3: '[hh:mm] Time of regeneration 3',
  icalcregd: '[yyyy.mm.dd] Date',
  idos: 'Status Dosiergerät',
  ierrmemclear: '[yyyy.mm.dd hh:mm] Error memory last deleted',
  ihwversioncl: 'Hardware version',
  iiqcomfort: 'An IQ-Comfort angeschlossene Geräte',
  ilastservice: '[yyyy.mm.dd] Last maintenance',
  isncu: 'Controller serial number',
  istartup: '[yyyy.mm.dd] Date of Start-up',
  iswupdate: 'Software update',
  iswversion: 'Software version',
  itimezone: '[h] Current time zone',
  itype: 'System type',
  iurlcloud1: 'URL Cloud',
  mcapacity: '[m³x°dH] Capacity figure',
  mcountreg: 'regeneration counter',
  mcountwater1: '[l] Soft water exchanger 1',
  mcountwater2: '[l] Soft water exchanger 2',
  mcountwatertank: '[l] Make-up water volume',
  mcurrent: '[mA] Chlorine current',
  mendreg1: '[hh:mm] Last regeneration Exchanger 1',
  mendreg2: '[hh:mm] Last regeneration Exchanger 2',
  mflow1: '[m³/h] Flow rate exch. 1',
  mflow2: '[m³/h] Flow rate exch. 2',
  mflowblend: '[m³/h] Blending flow rate',
  mflowexc: '[Min] during',
  mflowexc1reg2: '[Min]',
  mflowexc2reg1: '[Min]',
  mflowmax: '[m³/h] Flow rate peak value',
  mflowmax1reg2: '[m³/h] Exchanger 1 peak value',
  mflowmax2reg1: '[m³/h] Exchanger 2 peak value',
  mflowreg1: '[l/h] Regeneration flow rate Exchanger 1',
  mflowreg2: '[l/h] Regeneration flow rate Exchanger 2',
  mhardsoftw: '[°dh] Actual value soft water hardness',
  mlifeadsorb: '[%] Adsorber exhausted by',
  mmaint: '[d] Perform maintenance in',
  mregpercent1: '[%]',
  mregpercent2: '[%]',
  mregstatus: 'Regeneration step',
  mremregstep: 'Remaining amount / time of current regeneration step',
  mrescapa1: '[m³] Soft water Exchanger 1',
  mrescapa2: '[m³] Soft water Exchanger 2',
  mresidcap1: '[%] Residual capacity 1',
  mresidcap2: '[%] Residual capacity 2',
  mreswatadmod: '[m³] Adsorber remaining amount of water',
  msaltrange: '[d] Salt-reach',
  msaltusage: '[kg] salt consumption',
  mstep1: 'Step indication regeneration valve 1',
  mstep2: 'Step indication regeneration valve 2',
  pbackwash: '[l] Backwash',
  pbuzzer: 'Audio signal',
  pbuzzfrom: '[hh:mm] Audio signal release from',
  pbuzzto: '[hh:mm] Audio signal release until',
  pcfcontact: 'Function fault signal contact',
  pclearcntreg: 'Reset regeneration counter',
  pclearcntwater: 'Reset water meter',
  pclearerrmem: 'Delete error memory',
  pcurrent: '[mA] Setpoint current',
  pdate: '[yyyy.mm.dd] Current date',
  pdlstauto: 'Switch-over DST to ST',
  pforcedregdist: '[d] Interval of forced regeneration',
  pfreqblendvalve: '[Hz] End frequency blending valve',
  pfreqregvalve: '[Hz] End frequency regeneration valve',
  phunit: 'Hardness unit',
  pknx: 'KNX connection',
  planguage: 'Current language',
  pled: 'Illuminated LED ring',
  pledatsaltpre: 'Illuminated LED ring flashes on signal',
  pledbright: '[%] Brightness',
  pload: '[mAMin] Charge',
  pmailadress: '',
  pmaintint: '[d] Maintenance interval',
  pmaxdurdisinfect: '[Min] Longest switch-on time Cl cell',
  pmaxresdurreg: '[Min] Max Remaining time regeneration',
  pmaxvolmaxcap: '[l] Max. filling volume largest cap',
  pmaxvolmincap: '[l] Max. filling volume smallest cap',
  pminvolmaxcap: '[l] Min. filling volume largest cap',
  pminvolmincap: '[l] Min. filling volume smallest cap',
  pmode: '',
  pmodedesinf: 'Activate/deactivate chlorine cell',
  pmodefr: 'Indiv. Operating mode Friday',
  pmodemo: 'Indiv. Operating mode Monday',
  pmodesa: 'Indiv. Operating mode Saturday',
  pmodesu: 'Indiv. Operating mode Sunday',
  pmodeth: 'Indiv. Operating mode Thursday',
  pmodetu: 'Indiv. Operating mode Tuesday',
  pmodewe: 'Indiv. Operating mode Wednesday',
  pmonblend: 'Blending monitoring',
  pmondisinf: 'Disinfection monitoring',
  pmonflow: 'Monitoring of nominal flow',
  pmonregmeter: '[Min] Regeneration monitoring time',
  pmonsalting: '[Min] Salting monitoring time',
  pname: 'Name',
  pnomflow: '[m³/h] Nominal flow rate',
  pntpsync: 'Get date/time automatically (NTP)',
  poverload: 'System overloaded',
  ppowerfail: 'Reaction to power failure > 5 min',
  pprateblending: '[l/Imp] Blending water meter pulse rate',
  pprateregwater: '[l/Imp] Regeneration water meter pulse rate',
  ppratesoftwater: '[l/Imp] Soft water meter pulse rate',
  pprogin: 'Programmable input function',
  pprogout: 'Programmable output function',
  prawhard: '[°dH] Raw water hardness',
  pregmo1: '[hh:mm] Define time of regeneration 1',
  pregmo2: '[hh:mm] Define time of regeneration 2',
  pregmo3: '[hh:mm] Define time of regeneration 3',
  pregmode: 'Time of regeneration',
  prescaplimit: '[%] Residual capacity limit value',
  prinsing: '[Min] Slow rinse',
  psetcapfr: '[m³x°dH] Capacity figure Friday',
  psetcapmo: '[m³x°dH] Capacity figure Monday',
  psetcapsa: '[m³x°dH] Capacity figure Saturday',
  psetcapsu: '[m³x°dH] Capacity figure Sunday',
  psetcapth: '[m³x°dH] Capacity figure Thursday',
  psetcaptu: '[m³x°dH] Capacity figure Tuesday',
  psetcapwe: '[m³x°dH] Capacity figure Wednesday',
  psetsoft: '[°dH] Setpoint of soft water hardness',
  ptelnr: 'Tel. no.',
  ptime: '[hh:mm] Current time',
  pvolume: '[m³] Adsorber treatment volume',
  pwashingout: '[l] Washing out',
};
